### ISSUE TITLE
Ejercicio 2

### ISSUE THREAD

**Issue by chiarab22** [Patriesc/T7_POO#1]
@Patriesc El ejercicio 2 funciona como lo he subido. Pero en el case 1 si trasladamos el foreach en un método de la clase cliente no imprime nada. 
Quería averiguarlo.

**Comment by Patriesc** [comment]
La lista está creada en la clase Ejercicio2, entonces como mucho podrías hacer un método en la clase Cliente para mostrarlo, pero para recorrer la lista tienes que hacerlo en la clase donde la hayas creado.
